development:
  adapter: postgresql
  encoding: utf8
  database: invoice_development
  username: myapp 
  password: qwe
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: invoice_test
  username: myapp  
  password: qwe
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: invoice_production
  username: myapp 
  password: qwe 
  host: localhost
